---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubedemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubedemo
    spec:
      containers:
      - name: kubedemo
        image: rramkumar86/kubedemo:latest
        ports:
        - containerPort: 80
  
---
apiVersion: v1
kind: Service
metadata:
  name: webapp1-svc
  labels:
    app: kubedemo
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8084
  selector:
    app: kubedemo
    type: LoanBalancer
